# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               Longevity Genomics
tagline:             'Integrative genomic resource to develop translational strategies to promote longevity'
description:         'Navigation'
url:                 https://DanielEvansLab.github.io
baseurl:             ''
gems:                [jekyll-paginate, jekyll-gist]
paginate:            5

# About/contact
author:
  name:              Dan Evans
  url:               http://danielevanslab.github.io/
  email:             devans@psg.ucsf.edu

# Custom vars
version:             Lanyon
